services:
  - type: web
    name: ballerine-back-office
    runtime: docker
    region: ohio
    dockerfilePath: ./apps/backoffice-v2/Dockerfile
    dockerContext: ./apps/backoffice-v2
    buildCommand: docker build --build-arg NPM_LOG_LEVEL=notice .
    plan: starter
    envVars:
      - key: PORT
        value: 80
      - key: VITE_API_URL
        value: https://ballerine-workflow-service.onrender.com/api/v1/
      - key: VITE_API_KEY
        value: secret
      - key: VITE_ENVIRONMENT_NAME
        value: production

  - type: web
    name: ballerine-kyb-app
    runtime: docker
    region: ohio
    dockerfilePath: ./apps/kyb-app/Dockerfile
    dockerContext: ./apps/kyb-app
    buildCommand: docker build --build-arg NPM_LOG_LEVEL=notice .
    plan: starter
    envVars:
      - key: PORT
        value: 80
      - key: VITE_API_URL
        value: https://ballerine-workflow-service.onrender.com/api/v1/
      - key: VITE_API_KEY
        value: secret
      - key: VITE_ENVIRONMENT_NAME
        value: production
      - key: VITE_KYB_API_URL
        value: https://ballerine-workflow-service.onrender.com/api/v1/

  - type: web
    name: ballerine-workflows-dashboard
    runtime: docker
    region: ohio
    dockerfilePath: ./apps/workflows-dashboard/Dockerfile
    dockerContext: ./apps/workflows-dashboard
    buildCommand: docker build --build-arg NPM_LOG_LEVEL=notice .
    plan: starter
    envVars:
      - key: PORT
        value: 80
      - key: VITE_API_URL
        value: https://ballerine-workflow-service.onrender.com/api/v1/
      - key: VITE_API_KEY
        value: secret
      - key: VITE_ENVIRONMENT_NAME
        value: production
      - key: VITE_KYB_API_URL
        value: https://ballerine-workflow-service.onrender.com/api/v1/
      - key: VITE_IMAGE_LOGO_URL
        value: https://raw.githubusercontent.com/vault-pay/logo/a53fe08f64054061fe5b7ad9e61a05b7d4416ca0/vaultpay-new-large-logo.png

  - type: web
    name: ballerine-workflow-service
    runtime: docker
    dockerfilePath: ./Dockerfile.workflow-service
    dockerContext: .
    plan: starter
    region: ohio
    envVars:
      - key: PORT
        value: 3000
      - key: BCRYPT_SALT
        sync: false
      - key: SESSION_EXPIRATION_IN_MINUTES
        sync: false
      - key: DB_URL
        value: postgres://admin:admin@ballerine-postgres:5432/postgres
      - key: DB_USER
        value: admin
      - key: DB_PASSWORD
        value: admin
      - key: DB_PORT
        value: 5432
      - key: API_KEY
        sync: false
      - key: NODE_ENV
        sync: false
      - key: COMPOSE_PROJECT_NAME
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: BACKOFFICE_CORS_ORIGIN
        value: https://ballerine-back-office.onrender.com
      - key: WORKFLOW_DASHBOARD_CORS_ORIGIN
        value: https://ballerine-workflows-dashboard.onrender.com
      - key: KYB_EXAMPLE_CORS_ORIGIN
        value: https://ballerine-kyb-app.onrender.com
      - key: APP_API_URL
        value: https://ballerine-workflow-service.onrender.com
      - key: EMAIL_API_TOKEN
        value: ''
      - key: EMAIL_API_URL
        value: https://api.sendgrid.com/v3/mail/send
      - key: UNIFIED_API_URL
        value: https://ballerine-workflow-service.onrender.com
      - key: UNIFIED_API_TOKEN
        value: 'secret'
      - key: UNIFIED_API_SHARED_SECRET
        value: 'secret'
      - key: ENVIRONMENT_NAME
        value: production
      - key: HASHING_KEY_SECRET
        sync: false
      - key: HASHING_KEY_SECRET_BASE64
        sync: false
      - key: NOTION_API_KEY
        sync: false
      - key: DOMAIN_NAME
        value: https://ballerine-workflow-service.onrender.com

  - type: web
    name: ballerine-postgres
    runtime: image
    region: ohio
    image:
      url: docker.io/sibedge/postgres-plv8:15.3-3.1.7
    plan: starter
    envVars:
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        value: admin
      - key: PATH
        value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - key: LANG
        value: en_US.utf8
      - key: PG_MAJOR
        value: "15"
      - key: PG_VERSION
        value: "15.3"
      - key: PG_SHA256
        value: ffc7d4891f00ffbf5c3f4eab7fbbced8460b8c0ee63c5a5167133b9e6599d932
      - key: DOCKER_PG_LLVM_DEPS
        value: llvm15-dev clang15
      - key: PGDATA
        value: /var/lib/postgresql/data
      - key: PLV8_VERSION
        value: "3.1.7"
      - key: PORT
        value: "5432"

version: "1"
