services:
  - type: web
    name: vaultpay-back-office
    runtime: docker
    region: ohio
    dockerfilePath: ./apps/backoffice-v2/Dockerfile
    dockerContext: ./apps/backoffice-v2
    buildCommand: docker build
    plan: starter
    envVars:
      - key: PORT
        value: 80
      - key: VITE_API_URL
        value: http://ballerine-backend.onrender.com/api/v1/
      - key: VITE_API_KEY
        value: secret
      - key: VITE_AUTH_ENABLED
        value: "false"
      - key: VITE_MOCK_SERVER
        value: "false"
      - key: VITE_FETCH_SIGNED_URL
        value: "false"
      - key: VITE_ENVIRONMENT_NAME
        value: development

  - type: web
    name: ballerine-kyb
    runtime: docker
    region: ohio
    dockerfilePath: ./apps/kyb-app/Dockerfile
    dockerContext: ./apps/kyb-app
    buildCommand: docker build
    plan: starter
    envVars:
      - key: PORT
        value: 80
      - key: VITE_API_URL
        value: http://ballerine-backend.onrender.com/api/v1/
      - key: VITE_API_KEY
        value: secret
      - key: VITE_AUTH_ENABLED
        value: "true"
      - key: VITE_MOCK_SERVER
        value: "false"
      - key: VITE_ENVIRONMENT_NAME
        value: local

  - type: web
    name: ballerine-dashboard
    runtime: docker
    region: ohio
    dockerfilePath: ./apps/workflows-dashboard/Dockerfile
    dockerContext: ./apps/workflows-dashboard
    buildCommand: docker build --build-arg NPM_LOG_LEVEL=notice .
    plan: starter
    envVars:
      - key: PORT
        value: 80
      - key: VITE_API_URL
        value: http://ballerine-backend.onrender.com/api/v1/
      - key: VITE_AUTH_ENABLED
        value: "true"
      - key: VITE_MOCK_SERVER
        value: "false"
      - key: VITE_FETCH_SIGNED_URL
        value: "false"
      - key: VITE_ENVIRONMENT_NAME
        value: local

  - type: web
    name: ballerine-backend
    runtime: docker
    dockerfilePath: ./services/workflows-service/Dockerfile
    dockerContext: ./services/workflows-service
    buildCommand: docker build
    plan: starter
    region: ohio
    envVars:
      - key: PORT
        value: 3000
      - key: BACKOFFICE_CORS_ORIGIN
        value: https://vaultpay-back-office.onrender.com
      - key: WORKFLOW_DASHBOARD_CORS_ORIGIN
        value: https://ballerine-dashboard.onrender.com
      - key: APP_API_URL
        value: https://ballerine-backend.onrender.com
      - key: BCRYPT_SALT
        value: 10
      - key: SESSION_EXPIRATION_IN_MINUTES
        value: 60
      - key: DB_URL
        value: postgres://admin:admin@ballerine-database:5432/postgres
      - key: DB_USER
        value: admin
      - key: DB_PASSWORD
        value: admin
      - key: DB_PORT
        value: 5432
      - key: API_KEY
        value: secret
      - key: NODE_ENV
        value: development
      - key: SESSION_SECRET
        value: secret
      - key: UNIFIED_API_URL
        value: https://ballerine-backend.onrender.com
      - key: UNIFIED_API_TOKEN
        value: secret-key
      - key: UNIFIED_API_SHARED_SECRET
        value: shared-secret-key
      - key: ENVIRONMENT_NAME
        value: development
      - key: HASHING_KEY_SECRET
        value: secret
      - key: HASHING_KEY_SECRET_BASE64
        value: JDJiJDEwJG5pa1M5L2NPSndQa2E0bG15b3F0V2U=
      - key: NOTION_API_KEY
        value: secret
      - key: DOMAIN_NAME
        value: https://ballerine-backend.onrender.com
      - key: KYB_EXAMPLE_CORS_ORIGIN
        value: https://vaultpay-back-office.onrender.com

  - type: web
    name: ballerine-database
    runtime: image
    region: ohio
    image:
      url: docker.io/sibedge/postgres-plv8:15.3-3.1.7
    plan: starter
    envVars:
      - key: POSTGRES_USER
        value: admin
      - key: POSTGRES_PASSWORD
        value: admin
      - key: PORT
        value: "5432"

version: "1"